import {Outfit} from "next/font/google";
import "./globals.css";
import DbProviderClient from "../components/DbProviderClient";

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={`${outfit.variable} antialiased`}>
                <DbProviderClient>{children}</DbProviderClient>
            </body>
        </html>
    );
}
